/**
 * Từ khoá tiếng Việt cho các emoji/sticker hay tìm nhất — dùng để lọc khi
 * gõ vào ô tìm kiếm picker. Emoji không có trong bảng vẫn tìm được qua tên
 * nhóm (label) làm fallback, xem SocialEmojiPicker.vue::matchesQuery().
 */
export const EMOJI_KEYWORDS = {
  '😀': 'cười vui',
  '😃': 'cười vui mừng',
  '😄': 'cười tươi',
  '😁': 'cười toe toét',
  '😆': 'cười lớn',
  '😅': 'cười mồ hôi ngại',
  '🤣': 'cười lăn cười bò',
  '😂': 'cười ra nước mắt',
  '🙂': 'cười nhẹ',
  '🙃': 'cười ngược',
  '😉': 'nháy mắt',
  '😊': 'cười hiền',
  '😇': 'thiên thần trong sáng',
  '🥰': 'yêu thương cưng',
  '😍': 'yêu thích mắt tim',
  '🤩': 'ngôi sao phát cuồng',
  '😘': 'hôn gió',
  '😋': 'ngon thèm',
  '😛': 'lè lưỡi',
  '😜': 'lè lưỡi nháy mắt',
  '🤪': 'điên khùng',
  '😝': 'lè lưỡi trêu',
  '🤑': 'tiền giàu',
  '🤗': 'ôm',
  '🤭': 'che miệng ngại',
  '🤫': 'suỵt im lặng',
  '🤔': 'suy nghĩ',
  '🤐': 'khoá miệng im lặng',
  '🤨': 'nghi ngờ nhướng mày',
  '😐': 'mặt vô cảm',
  '😑': 'mặt chán',
  '😶': 'không nói gì',
  '😏': 'cười khẩy',
  '😒': 'khó chịu chán',
  '🙄': 'trợn mắt',
  '😬': 'nhăn răng ngại',
  '😌': 'nhẹ nhõm hài lòng',
  '😔': 'buồn suy tư',
  '😪': 'buồn ngủ',
  '🤤': 'chảy nước dãi thèm',
  '😴': 'ngủ',
  '😷': 'khẩu trang bệnh',
  '🤒': 'sốt bệnh',
  '🤕': 'đau băng bó',
  '🤢': 'buồn nôn',
  '🤮': 'nôn mửa',
  '🤧': 'hắt xì cảm',
  '🥵': 'nóng',
  '🥶': 'lạnh',
  '🥴': 'chóng mặt say',
  '😵': 'choáng váng',
  '🤯': 'nổ não sốc',
  '🤠': 'cao bồi',
  '🥳': 'ăn mừng tiệc tùng',
  '😎': 'ngầu kính râm',
  '🤓': 'mọt sách',
  '🧐': 'xem xét kính lúp',
  '😕': 'bối rối',
  '😟': 'lo lắng',
  '🙁': 'buồn',
  '☹️': 'buồn thất vọng',
  '😮': 'ngạc nhiên',
  '😯': 'ngạc nhiên im lặng',
  '😲': 'sốc kinh ngạc',
  '😳': 'đỏ mặt ngại ngùng',
  '🥺': 'nài nỉ đáng thương',
  '🥹': 'cố kìm nước mắt xúc động',
  '😦': 'hoảng sợ',
  '😧': 'đau khổ',
  '😨': 'sợ hãi',
  '😰': 'lo sợ toát mồ hôi',
  '😥': 'buồn thất vọng',
  '😢': 'khóc',
  '😭': 'khóc to',
  '😱': 'hét sợ hãi',
  '😖': 'khó chịu bối rối',
  '😣': 'kiên trì chịu đựng',
  '😞': 'thất vọng',
  '😓': 'mệt mỏi toát mồ hôi',
  '😩': 'mệt mỏi than',
  '😫': 'kiệt sức',
  '🥱': 'ngáp buồn ngủ',
  '😤': 'tức giận hừ',
  '😡': 'giận dữ đỏ mặt',
  '😠': 'tức giận',
  '🤬': 'chửi tục giận điên',
  '😈': 'quỷ tinh nghịch',
  '💀': 'đầu lâu chết',
  '💩': 'phân cứt',
  '👻': 'ma',
  '👽': 'người ngoài hành tinh',
  '🤖': 'robot',
  '🎃': 'halloween bí ngô',
  '👍': 'like đồng ý tốt',
  '👎': 'dislike không đồng ý',
  '👏': 'vỗ tay khen',
  '🙌': 'giơ tay ăn mừng',
  '🫶': 'trái tim tay yêu',
  '👐': 'mở tay',
  '🤲': 'lòng bàn tay cầu nguyện',
  '🤝': 'bắt tay hợp tác',
  '🙏': 'cảm ơn cầu nguyện chắp tay',
  '👋': 'vẫy tay chào',
  '✌️': 'chữ v chiến thắng',
  '🤞': 'bắt chéo ngón tay may mắn',
  '🤟': 'yêu tay',
  '🤘': 'rock nhạc',
  '🤙': 'gọi điện',
  '👈': 'trỏ trái',
  '👉': 'trỏ phải',
  '👆': 'trỏ lên',
  '👇': 'trỏ xuống',
  '☝️': 'giơ một ngón',
  '✊': 'nắm đấm cổ vũ',
  '👊': 'đấm',
  '💪': 'cơ bắp mạnh mẽ cố lên',
  '👀': 'mắt nhìn',
  '💃': 'nhảy múa',
  '🕺': 'nhảy múa',
  '💅': 'sơn móng tay điệu',
  '❤️': 'trái tim đỏ yêu',
  '🧡': 'trái tim cam',
  '💛': 'trái tim vàng',
  '💚': 'trái tim xanh lá',
  '💙': 'trái tim xanh dương',
  '💜': 'trái tim tím',
  '🖤': 'trái tim đen',
  '🤍': 'trái tim trắng',
  '💔': 'trái tim vỡ buồn',
  '❤️‍🔥': 'trái tim lửa cháy',
  '💕': 'hai trái tim yêu',
  '💞': 'trái tim xoay',
  '💓': 'trái tim đập',
  '💗': 'trái tim lớn dần',
  '💖': 'trái tim lấp lánh',
  '💘': 'trái tim mũi tên',
  '💝': 'trái tim nơ quà',
  '✨': 'lấp lánh đẹp',
  '🔥': 'lửa hot cháy',
  '⭐': 'ngôi sao',
  '🌟': 'ngôi sao sáng',
  '💯': 'trăm điểm hoàn hảo',
  '💤': 'ngủ zzz',
  '🎉': 'chúc mừng tiệc',
  '🎊': 'chúc mừng confetti',
  '🎈': 'bóng bay sinh nhật',
  '🎁': 'quà tặng',
  '🎀': 'nơ',
  '🎂': 'bánh sinh nhật',
  '🧁': 'bánh cupcake',
  '🍰': 'bánh kem',
  '🥳': 'ăn mừng tiệc',
  '🥂': 'ly rượu chúc mừng',
  '🍾': 'sâm panh',
  '🏆': 'cúp vô địch',
  '🥇': 'huy chương vàng',
  '🎯': 'mục tiêu bắn trúng',
  '🎮': 'chơi game',
  '🎲': 'xúc xắc',
  '👑': 'vương miện',
  '💍': 'nhẫn cưới',
  '💐': 'bó hoa',
  '🌹': 'hoa hồng',
  '🌸': 'hoa anh đào',
  '🌻': 'hoa hướng dương',
  '🐶': 'chó cún',
  '🐱': 'mèo',
  '🐭': 'chuột',
  '🐹': 'chuột hamster',
  '🐰': 'thỏ',
  '🦊': 'cáo',
  '🐻': 'gấu',
  '🐼': 'gấu trúc panda',
  '🐨': 'gấu koala',
  '🐯': 'hổ',
  '🦁': 'sư tử',
  '🐮': 'bò',
  '🐷': 'heo lợn',
  '🐸': 'ếch',
  '🐵': 'khỉ',
  '🐔': 'gà',
  '🐧': 'chim cánh cụt',
  '🦆': 'vịt',
  '🦄': 'kỳ lân',
  '🐝': 'ong',
  '🦋': 'bướm',
  '🐢': 'rùa',
  '🐙': 'bạch tuộc',
  '🐬': 'cá heo',
  '🐳': 'cá voi',
  '✅': 'đúng đồng ý xong',
  '❌': 'sai không',
  '❗': 'chú ý cảnh báo',
  '❓': 'hỏi thắc mắc',
  '💡': 'ý tưởng bóng đèn',
  '🚀': 'tên lửa nhanh',
  '🎓': 'tốt nghiệp học',
  '🏫': 'trường học',
  '📚': 'sách vở học',
  '📖': 'đọc sách',
  '✏️': 'bút chì viết',
  '📝': 'ghi chú viết',
  '📌': 'ghim đánh dấu',
  '💻': 'máy tính laptop',
  '📱': 'điện thoại',
  '☕': 'cà phê',
  '🍕': 'pizza',
  '🍔': 'hamburger',
  '🍜': 'mì phở',
  '🍦': 'kem',
  '🎵': 'nhạc',
  '🎤': 'hát mic',
  '⚽': 'bóng đá',
  '🏀': 'bóng rổ',
  '✈️': 'máy bay du lịch',
  '🚗': 'xe hơi ô tô',
  '☀️': 'nắng mặt trời',
  '🌈': 'cầu vồng',
  '☔': 'mưa ô dù',
  '❄️': 'tuyết lạnh',
  '🇻🇳': 'cờ việt nam',
};
